print("Suma")
print(2+3)
print("Resta")
print(2-3)
print("Divicion")
print(5/2)
print("Multiplicacion")
print(3*4)
print("Divicion entera")
print(5//2)
print("Divicion modulo")
print(5%2)
print("Exponencial")
print(2**3)
print("Raiz cuadrada")
import math
print(math.sqrt(16))
print(pow(4,0.5))
#REGLAS DE PROCEDENCIA
print("Reglas de calculo")
print(5+5*2)